apiVersion: apps/v1
kind: Deployment
metadata:
  name: player-service
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: player-service
  template:
    metadata:
      labels:
        app: player-service
    spec:
      containers:
      - image: docker.io/cboisvert/player-service:latest
        name: player-service
        ports:
        - containerPort: 80
