apiVersion: v2
name: player-service
version: 0.0.1
dependencies: # A list of the chart requirements (optional)
  - name: kafka
    version: "7.1.13"
    repository: https://charts.bitnami.com/bitnami
    condition: dep-kafka.enabled
    alias: dep-kafka